/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myproject;

import java.util.Scanner;

public class App {
   public static void main(String[] args) {
     
     java.util.Scanner keyboard = new java.util.Scanner(System.in);
     
     System.out.print("제품명? ");
     String snid = keyboard.nextLine();
     
     System.out.print("설명? ");
     String description = keyboard.nextLine();
     
     System.out.print("출시정보? ");
     String release = keyboard.nextLine();
     
     System.out.print("가격? ");
     String price = keyboard.nextLine();
     
     System.out.print("응모시작? ");
     String startData = keyboard.nextLine();
     
     System.out.print("응모 끝? ");
     String endData = keyboard.nextLine();
     
     System.out.print("당첨자발표? ");
     String anno = keyboard.nextLine();
     
     System.out.println();
     
     
     System.out.printf("제품명: %s\n", snid);
     System.out.printf("설명: %s\n", description);
     System.out.printf("출시정보: %s\n", release);
     System.out.printf("가격: %s\n", price);
     System.out.printf("응모시작: %s\n", startData);
     System.out.printf("응모 끝: %s\n", endData);
     System.out.printf("응모기간: %s ~ %s\n", startData, endData);
     System.out.printf("당첨자발표: %s\n", anno);
     
     keyboard.close();
     
     
     
    }
}
