/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myproject;

import java.util.Scanner;

public class App {
   public static void main(String[] args) {
     Scanner keyboard = new Scanner(System.in);
     
     final int size = 100;
     
     String[] brand = new String[size];
     String[] sneakersname = new String[size];
     int[] releaseMonth = new int[size];
     int[] price = new int[size];     
     
     String response;
     
     int count = 0;
     for (int i = 0; i < 10; i++) {
       
       System.out.print("브랜드명? ");
       brand[i] = keyboard.next();
       keyboard.nextLine();
    
       System.out.print("신발명? ");
       sneakersname[i] = keyboard.nextLine();

       System.out.print("출시월? ");
       releaseMonth[i] = keyboard.nextInt();
       keyboard.nextLine();
       
       System.out.print("가격? ");
       price[i] = keyboard.nextInt();
       
       count++;
       
       System.out.print("계속 입력 하시겠습니까? (y/n)");
       
       System.out.println();
       response = keyboard.next();
       
       if (!response.equalsIgnoreCase("y")) {
         break;
       }
     }
     
     System.out.println();
     
     for (int i = 0; i < count; i++) {
     
       System.out.printf("%s, %s, %d, %d\n", brand[i], sneakersname[i], releaseMonth[i], price[i]);
     System.out.println();  
     }
     
     keyboard.close();
     
    }
}
