/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myproject;

import java.util.Scanner;

public class App {
  public static void main(String[] args) {
    Scanner keyboard = new Scanner(System.in);

    class Information {
      String brand;
      String sneakersName;
      String releaseMonth;
      String price;
    }

    final int SIZE = 100;

    Information[] box1 = new Information[SIZE];

    int count = 0;

    String response;

    for (int i = 0; i < 100; i++) {

      count++;

      Information box2 = new Information();

      System.out.print("브랜드명? ");
      box2.brand = keyboard.next();
      keyboard.nextLine();

      System.out.print("신발명? ");
      box2.sneakersName = keyboard.nextLine();

      System.out.print("출시월? ");
      box2.releaseMonth = keyboard.nextLine();
      keyboard.nextLine();

      System.out.print("가격? ");
      box2.price = keyboard.nextLine();

      box1[i] = box2;


      System.out.print("계속 입력 하시겠습니까? (y/n)");

      System.out.println();

      response = keyboard.next();

      if (!response.equalsIgnoreCase("y")) {
        break;
      }
    }

      keyboard.close();

      System.out.println();

      for (int i = 0; i < count; i++) {

        Information box2 = box1[i];

        System.out.printf("%s, %s, %s, %s\n", 
            box2.brand, box2.sneakersName, box2.releaseMonth, box2.price);



      }
    }
  }




